=== osmarAnt/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombrecompleto, correo, telefono, cumpleaños)>
<!ELEMENT nombrecompleto (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumpleaños (año, mes, día)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT día (#PCDATA)>

=== osmarAnt/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombrecompleto>
        <nombre>Rafael</nombre>
        <apellido>R C</apellido>
    </nombrecompleto>
    <correo>rrojano@ejemplo.com</correo>
    <telefono>5555512345</telefono>
    <cumpleaños>
        <año>1990</año>
        <mes>5</mes>
        <día>15</día>
    </cumpleaños>
</direccion>
